= Broker-marketdata

* This component is used to normalize prices from BitMex to internal quotes.
* It has a client websocket that connects to BitMex.
* Data received is sent via vertx bus to two topics:

    Topic: raw_data
        * raw quotes recevied from BitMex are logged asynchronous for audit

* Quotes are normalized into a Google Proto Buffer object and this object is sent
to a different topic simultaneously:

   Topic: internal_quotes
        * Two components are reading from this topic
        1) Storage that stores the internal normilized prices
        2) Websocket server, this component publish the mesages to clients
        subscribed for internal use



BitMex API:

    https://www.bitmex.com/app/apiOverview

It subscribes to topic instrument updates via Websockets:

    https://www.bitmex.com/app/wsAPI

Connection to:

    wss://www.bitmex.com/realtime

Topic:

    "instrument",          // Instrument updates including turnover and bid/ask

To manage the configuration of the topics it can be changed in the file:

    broker-marketdata/src/main/resources/application.ymal

In to the property definition:

    ws.client.symbol


= Vertx

image:https://img.shields.io/badge/vert.x-4.2.0-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean compile exec:java
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]

= Google Protocol Buffers

== Building

To build InternalPrice.proto:

* Add the environment variable PROTOC_PATH where protoc in installed.
* Go to terminal in the project and execute
```
.\build_protoc.bat
```
* It will create the relevant classes for InternalPrice.
* InternalPrice is the serialized object that will be sent.
* For debugging you can set the variable serialization:false in the config file

== Help

https://developers.google.com/protocol-buffers/docs/javatutorial


= Storage

* Uses PostgreSql to store prices as docker image
* Uses flyway as a database management control


= Build Containers

== Building

* Go to <WORKSPACE>/broker_marketdata/cocker-compose/marketdata
* execute

```
broker-marketdata\docker-compose\marketdata\
docker-compose up -d
```

* it will deploy the container with market-data-service and posgress
* to test the websocket connect using https://websocketking.com/

```
ws://localhost:8900/realtime/quotes
```


