// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalQuote.proto

package org.broker.marketdata.protos;

public final class InternalQuote {
  private InternalQuote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marketdata_Quote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marketdata_Quote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023InternalQuote.proto\022\nmarketdata\"\354\001\n\005Qu" +
      "ote\022\016\n\006source\030\001 \002(\t\022\r\n\005topic\030\002 \002(\t\022\016\n\006sy" +
      "mbol\030\003 \002(\t\022\016\n\006action\030\004 \002(\t\022\021\n\tmarkPrice\030" +
      "\005 \001(\001\022\020\n\010bidPrice\030\006 \001(\001\022\020\n\010midPrice\030\007 \001(" +
      "\001\022\020\n\010askPrice\030\010 \001(\001\022\016\n\006volume\030\t \001(\001\022\027\n\017s" +
      "ourceTimestamp\030\n \001(\003\022\030\n\020arrivalTimestamp" +
      "\030\013 \001(\003\022\030\n\020publishTimestamp\030\014 \001(\003B/\n\034org." +
      "broker.marketdata.protosB\rInternalQuoteP" +
      "\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_marketdata_Quote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_marketdata_Quote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marketdata_Quote_descriptor,
        new java.lang.String[] { "Source", "Topic", "Symbol", "Action", "MarkPrice", "BidPrice", "MidPrice", "AskPrice", "Volume", "SourceTimestamp", "ArrivalTimestamp", "PublishTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
