// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalQuote.proto

package org.broker.marketdata.protos;

/**
 * Protobuf type {@code marketdata.Quote}
 */
public final class Quote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marketdata.Quote)
    QuoteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Quote.newBuilder() to construct.
  private Quote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Quote() {
    source_ = "";
    topic_ = "";
    action_ = "";
    stage_ = 0;
    symbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Quote();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Quote(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            quoteId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            source_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            stage_ = rawValue;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            symbol_ = s;
            break;
          }
          case 57: {
            bitField0_ |= 0x00000002;
            markPrice_ = input.readDouble();
            break;
          }
          case 65: {
            bitField0_ |= 0x00000004;
            bidPrice_ = input.readDouble();
            break;
          }
          case 73: {
            bitField0_ |= 0x00000008;
            midPrice_ = input.readDouble();
            break;
          }
          case 81: {
            bitField0_ |= 0x00000010;
            askPrice_ = input.readDouble();
            break;
          }
          case 89: {
            bitField0_ |= 0x00000020;
            volume_ = input.readDouble();
            break;
          }
          case 96: {
            bitField0_ |= 0x00000040;
            sourceTimestamp_ = input.readInt64();
            break;
          }
          case 104: {
            bitField0_ |= 0x00000080;
            arrivalTimestamp_ = input.readInt64();
            break;
          }
          case 112: {
            bitField0_ |= 0x00000100;
            publishTimestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.broker.marketdata.protos.InternalQuote.internal_static_marketdata_Quote_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.broker.marketdata.protos.InternalQuote.internal_static_marketdata_Quote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.broker.marketdata.protos.Quote.class, org.broker.marketdata.protos.Quote.Builder.class);
  }

  /**
   * Protobuf enum {@code marketdata.Quote.StageType}
   */
  public enum StageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RAW = 0;</code>
     */
    RAW(0),
    /**
     * <code>AGG = 1;</code>
     */
    AGG(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RAW = 0;</code>
     */
    public static final int RAW_VALUE = 0;
    /**
     * <code>AGG = 1;</code>
     */
    public static final int AGG_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StageType forNumber(int value) {
      switch (value) {
        case 0: return RAW;
        case 1: return AGG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StageType>() {
            public StageType findValueByNumber(int number) {
              return StageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.broker.marketdata.protos.Quote.getDescriptor().getEnumTypes().get(0);
    }

    private static final StageType[] VALUES = values();

    public static StageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:marketdata.Quote.StageType)
  }

  private int bitField0_;
  public static final int QUOTEID_FIELD_NUMBER = 1;
  private long quoteId_;
  /**
   * <code>int64 quoteId = 1;</code>
   * @return The quoteId.
   */
  @java.lang.Override
  public long getQuoteId() {
    return quoteId_;
  }

  public static final int SOURCE_FIELD_NUMBER = 2;
  private volatile java.lang.Object source_;
  /**
   * <code>string source = 2;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <code>string source = 2;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 3;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 3;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 3;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object action_;
  /**
   * <code>string action = 4;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 4;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAGE_FIELD_NUMBER = 5;
  private int stage_;
  /**
   * <code>.marketdata.Quote.StageType stage = 5;</code>
   * @return The enum numeric value on the wire for stage.
   */
  @java.lang.Override public int getStageValue() {
    return stage_;
  }
  /**
   * <code>.marketdata.Quote.StageType stage = 5;</code>
   * @return The stage.
   */
  @java.lang.Override public org.broker.marketdata.protos.Quote.StageType getStage() {
    @SuppressWarnings("deprecation")
    org.broker.marketdata.protos.Quote.StageType result = org.broker.marketdata.protos.Quote.StageType.valueOf(stage_);
    return result == null ? org.broker.marketdata.protos.Quote.StageType.UNRECOGNIZED : result;
  }

  public static final int SYMBOL_FIELD_NUMBER = 6;
  private volatile java.lang.Object symbol_;
  /**
   * <code>optional string symbol = 6;</code>
   * @return Whether the symbol field is set.
   */
  @java.lang.Override
  public boolean hasSymbol() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string symbol = 6;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>optional string symbol = 6;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MARKPRICE_FIELD_NUMBER = 7;
  private double markPrice_;
  /**
   * <code>optional double markPrice = 7;</code>
   * @return Whether the markPrice field is set.
   */
  @java.lang.Override
  public boolean hasMarkPrice() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional double markPrice = 7;</code>
   * @return The markPrice.
   */
  @java.lang.Override
  public double getMarkPrice() {
    return markPrice_;
  }

  public static final int BIDPRICE_FIELD_NUMBER = 8;
  private double bidPrice_;
  /**
   * <code>optional double bidPrice = 8;</code>
   * @return Whether the bidPrice field is set.
   */
  @java.lang.Override
  public boolean hasBidPrice() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional double bidPrice = 8;</code>
   * @return The bidPrice.
   */
  @java.lang.Override
  public double getBidPrice() {
    return bidPrice_;
  }

  public static final int MIDPRICE_FIELD_NUMBER = 9;
  private double midPrice_;
  /**
   * <code>optional double midPrice = 9;</code>
   * @return Whether the midPrice field is set.
   */
  @java.lang.Override
  public boolean hasMidPrice() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional double midPrice = 9;</code>
   * @return The midPrice.
   */
  @java.lang.Override
  public double getMidPrice() {
    return midPrice_;
  }

  public static final int ASKPRICE_FIELD_NUMBER = 10;
  private double askPrice_;
  /**
   * <code>optional double askPrice = 10;</code>
   * @return Whether the askPrice field is set.
   */
  @java.lang.Override
  public boolean hasAskPrice() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional double askPrice = 10;</code>
   * @return The askPrice.
   */
  @java.lang.Override
  public double getAskPrice() {
    return askPrice_;
  }

  public static final int VOLUME_FIELD_NUMBER = 11;
  private double volume_;
  /**
   * <code>optional double volume = 11;</code>
   * @return Whether the volume field is set.
   */
  @java.lang.Override
  public boolean hasVolume() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional double volume = 11;</code>
   * @return The volume.
   */
  @java.lang.Override
  public double getVolume() {
    return volume_;
  }

  public static final int SOURCETIMESTAMP_FIELD_NUMBER = 12;
  private long sourceTimestamp_;
  /**
   * <code>optional int64 sourceTimestamp = 12;</code>
   * @return Whether the sourceTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasSourceTimestamp() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int64 sourceTimestamp = 12;</code>
   * @return The sourceTimestamp.
   */
  @java.lang.Override
  public long getSourceTimestamp() {
    return sourceTimestamp_;
  }

  public static final int ARRIVALTIMESTAMP_FIELD_NUMBER = 13;
  private long arrivalTimestamp_;
  /**
   * <code>optional int64 arrivalTimestamp = 13;</code>
   * @return Whether the arrivalTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasArrivalTimestamp() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int64 arrivalTimestamp = 13;</code>
   * @return The arrivalTimestamp.
   */
  @java.lang.Override
  public long getArrivalTimestamp() {
    return arrivalTimestamp_;
  }

  public static final int PUBLISHTIMESTAMP_FIELD_NUMBER = 14;
  private long publishTimestamp_;
  /**
   * <code>optional int64 publishTimestamp = 14;</code>
   * @return Whether the publishTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasPublishTimestamp() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional int64 publishTimestamp = 14;</code>
   * @return The publishTimestamp.
   */
  @java.lang.Override
  public long getPublishTimestamp() {
    return publishTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (quoteId_ != 0L) {
      output.writeInt64(1, quoteId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, source_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, action_);
    }
    if (stage_ != org.broker.marketdata.protos.Quote.StageType.RAW.getNumber()) {
      output.writeEnum(5, stage_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, symbol_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeDouble(7, markPrice_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(8, bidPrice_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeDouble(9, midPrice_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeDouble(10, askPrice_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeDouble(11, volume_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt64(12, sourceTimestamp_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt64(13, arrivalTimestamp_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeInt64(14, publishTimestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (quoteId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, quoteId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, source_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, action_);
    }
    if (stage_ != org.broker.marketdata.protos.Quote.StageType.RAW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, stage_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, symbol_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, markPrice_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, bidPrice_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, midPrice_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, askPrice_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, volume_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, sourceTimestamp_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, arrivalTimestamp_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, publishTimestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.broker.marketdata.protos.Quote)) {
      return super.equals(obj);
    }
    org.broker.marketdata.protos.Quote other = (org.broker.marketdata.protos.Quote) obj;

    if (getQuoteId()
        != other.getQuoteId()) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (stage_ != other.stage_) return false;
    if (hasSymbol() != other.hasSymbol()) return false;
    if (hasSymbol()) {
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
    }
    if (hasMarkPrice() != other.hasMarkPrice()) return false;
    if (hasMarkPrice()) {
      if (java.lang.Double.doubleToLongBits(getMarkPrice())
          != java.lang.Double.doubleToLongBits(
              other.getMarkPrice())) return false;
    }
    if (hasBidPrice() != other.hasBidPrice()) return false;
    if (hasBidPrice()) {
      if (java.lang.Double.doubleToLongBits(getBidPrice())
          != java.lang.Double.doubleToLongBits(
              other.getBidPrice())) return false;
    }
    if (hasMidPrice() != other.hasMidPrice()) return false;
    if (hasMidPrice()) {
      if (java.lang.Double.doubleToLongBits(getMidPrice())
          != java.lang.Double.doubleToLongBits(
              other.getMidPrice())) return false;
    }
    if (hasAskPrice() != other.hasAskPrice()) return false;
    if (hasAskPrice()) {
      if (java.lang.Double.doubleToLongBits(getAskPrice())
          != java.lang.Double.doubleToLongBits(
              other.getAskPrice())) return false;
    }
    if (hasVolume() != other.hasVolume()) return false;
    if (hasVolume()) {
      if (java.lang.Double.doubleToLongBits(getVolume())
          != java.lang.Double.doubleToLongBits(
              other.getVolume())) return false;
    }
    if (hasSourceTimestamp() != other.hasSourceTimestamp()) return false;
    if (hasSourceTimestamp()) {
      if (getSourceTimestamp()
          != other.getSourceTimestamp()) return false;
    }
    if (hasArrivalTimestamp() != other.hasArrivalTimestamp()) return false;
    if (hasArrivalTimestamp()) {
      if (getArrivalTimestamp()
          != other.getArrivalTimestamp()) return false;
    }
    if (hasPublishTimestamp() != other.hasPublishTimestamp()) return false;
    if (hasPublishTimestamp()) {
      if (getPublishTimestamp()
          != other.getPublishTimestamp()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUOTEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuoteId());
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + STAGE_FIELD_NUMBER;
    hash = (53 * hash) + stage_;
    if (hasSymbol()) {
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
    }
    if (hasMarkPrice()) {
      hash = (37 * hash) + MARKPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMarkPrice()));
    }
    if (hasBidPrice()) {
      hash = (37 * hash) + BIDPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBidPrice()));
    }
    if (hasMidPrice()) {
      hash = (37 * hash) + MIDPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMidPrice()));
    }
    if (hasAskPrice()) {
      hash = (37 * hash) + ASKPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAskPrice()));
    }
    if (hasVolume()) {
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVolume()));
    }
    if (hasSourceTimestamp()) {
      hash = (37 * hash) + SOURCETIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSourceTimestamp());
    }
    if (hasArrivalTimestamp()) {
      hash = (37 * hash) + ARRIVALTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getArrivalTimestamp());
    }
    if (hasPublishTimestamp()) {
      hash = (37 * hash) + PUBLISHTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPublishTimestamp());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.broker.marketdata.protos.Quote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.broker.marketdata.protos.Quote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.broker.marketdata.protos.Quote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.broker.marketdata.protos.Quote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.broker.marketdata.protos.Quote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marketdata.Quote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marketdata.Quote)
      org.broker.marketdata.protos.QuoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.broker.marketdata.protos.InternalQuote.internal_static_marketdata_Quote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.broker.marketdata.protos.InternalQuote.internal_static_marketdata_Quote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.broker.marketdata.protos.Quote.class, org.broker.marketdata.protos.Quote.Builder.class);
    }

    // Construct using org.broker.marketdata.protos.Quote.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      quoteId_ = 0L;

      source_ = "";

      topic_ = "";

      action_ = "";

      stage_ = 0;

      symbol_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      markPrice_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000002);
      bidPrice_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000004);
      midPrice_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000008);
      askPrice_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      volume_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000020);
      sourceTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      arrivalTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      publishTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.broker.marketdata.protos.InternalQuote.internal_static_marketdata_Quote_descriptor;
    }

    @java.lang.Override
    public org.broker.marketdata.protos.Quote getDefaultInstanceForType() {
      return org.broker.marketdata.protos.Quote.getDefaultInstance();
    }

    @java.lang.Override
    public org.broker.marketdata.protos.Quote build() {
      org.broker.marketdata.protos.Quote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.broker.marketdata.protos.Quote buildPartial() {
      org.broker.marketdata.protos.Quote result = new org.broker.marketdata.protos.Quote(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.quoteId_ = quoteId_;
      result.source_ = source_;
      result.topic_ = topic_;
      result.action_ = action_;
      result.stage_ = stage_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.symbol_ = symbol_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.markPrice_ = markPrice_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bidPrice_ = bidPrice_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.midPrice_ = midPrice_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.askPrice_ = askPrice_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.volume_ = volume_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.sourceTimestamp_ = sourceTimestamp_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.arrivalTimestamp_ = arrivalTimestamp_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.publishTimestamp_ = publishTimestamp_;
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.broker.marketdata.protos.Quote) {
        return mergeFrom((org.broker.marketdata.protos.Quote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.broker.marketdata.protos.Quote other) {
      if (other == org.broker.marketdata.protos.Quote.getDefaultInstance()) return this;
      if (other.getQuoteId() != 0L) {
        setQuoteId(other.getQuoteId());
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (other.stage_ != 0) {
        setStageValue(other.getStageValue());
      }
      if (other.hasSymbol()) {
        bitField0_ |= 0x00000001;
        symbol_ = other.symbol_;
        onChanged();
      }
      if (other.hasMarkPrice()) {
        setMarkPrice(other.getMarkPrice());
      }
      if (other.hasBidPrice()) {
        setBidPrice(other.getBidPrice());
      }
      if (other.hasMidPrice()) {
        setMidPrice(other.getMidPrice());
      }
      if (other.hasAskPrice()) {
        setAskPrice(other.getAskPrice());
      }
      if (other.hasVolume()) {
        setVolume(other.getVolume());
      }
      if (other.hasSourceTimestamp()) {
        setSourceTimestamp(other.getSourceTimestamp());
      }
      if (other.hasArrivalTimestamp()) {
        setArrivalTimestamp(other.getArrivalTimestamp());
      }
      if (other.hasPublishTimestamp()) {
        setPublishTimestamp(other.getPublishTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.broker.marketdata.protos.Quote parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.broker.marketdata.protos.Quote) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long quoteId_ ;
    /**
     * <code>int64 quoteId = 1;</code>
     * @return The quoteId.
     */
    @java.lang.Override
    public long getQuoteId() {
      return quoteId_;
    }
    /**
     * <code>int64 quoteId = 1;</code>
     * @param value The quoteId to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteId(long value) {
      
      quoteId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 quoteId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuoteId() {
      
      quoteId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <code>string source = 2;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source = 2;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source = 2;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    /**
     * <code>string source = 2;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      source_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 3;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 3;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 4;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 4;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 4;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string action = 4;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private int stage_ = 0;
    /**
     * <code>.marketdata.Quote.StageType stage = 5;</code>
     * @return The enum numeric value on the wire for stage.
     */
    @java.lang.Override public int getStageValue() {
      return stage_;
    }
    /**
     * <code>.marketdata.Quote.StageType stage = 5;</code>
     * @param value The enum numeric value on the wire for stage to set.
     * @return This builder for chaining.
     */
    public Builder setStageValue(int value) {
      
      stage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.marketdata.Quote.StageType stage = 5;</code>
     * @return The stage.
     */
    @java.lang.Override
    public org.broker.marketdata.protos.Quote.StageType getStage() {
      @SuppressWarnings("deprecation")
      org.broker.marketdata.protos.Quote.StageType result = org.broker.marketdata.protos.Quote.StageType.valueOf(stage_);
      return result == null ? org.broker.marketdata.protos.Quote.StageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.marketdata.Quote.StageType stage = 5;</code>
     * @param value The stage to set.
     * @return This builder for chaining.
     */
    public Builder setStage(org.broker.marketdata.protos.Quote.StageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      stage_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.marketdata.Quote.StageType stage = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStage() {
      
      stage_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>optional string symbol = 6;</code>
     * @return Whether the symbol field is set.
     */
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string symbol = 6;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string symbol = 6;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string symbol = 6;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string symbol = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      bitField0_ = (bitField0_ & ~0x00000001);
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>optional string symbol = 6;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      symbol_ = value;
      onChanged();
      return this;
    }

    private double markPrice_ ;
    /**
     * <code>optional double markPrice = 7;</code>
     * @return Whether the markPrice field is set.
     */
    @java.lang.Override
    public boolean hasMarkPrice() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional double markPrice = 7;</code>
     * @return The markPrice.
     */
    @java.lang.Override
    public double getMarkPrice() {
      return markPrice_;
    }
    /**
     * <code>optional double markPrice = 7;</code>
     * @param value The markPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMarkPrice(double value) {
      bitField0_ |= 0x00000002;
      markPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double markPrice = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMarkPrice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      markPrice_ = 0D;
      onChanged();
      return this;
    }

    private double bidPrice_ ;
    /**
     * <code>optional double bidPrice = 8;</code>
     * @return Whether the bidPrice field is set.
     */
    @java.lang.Override
    public boolean hasBidPrice() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double bidPrice = 8;</code>
     * @return The bidPrice.
     */
    @java.lang.Override
    public double getBidPrice() {
      return bidPrice_;
    }
    /**
     * <code>optional double bidPrice = 8;</code>
     * @param value The bidPrice to set.
     * @return This builder for chaining.
     */
    public Builder setBidPrice(double value) {
      bitField0_ |= 0x00000004;
      bidPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double bidPrice = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBidPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bidPrice_ = 0D;
      onChanged();
      return this;
    }

    private double midPrice_ ;
    /**
     * <code>optional double midPrice = 9;</code>
     * @return Whether the midPrice field is set.
     */
    @java.lang.Override
    public boolean hasMidPrice() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double midPrice = 9;</code>
     * @return The midPrice.
     */
    @java.lang.Override
    public double getMidPrice() {
      return midPrice_;
    }
    /**
     * <code>optional double midPrice = 9;</code>
     * @param value The midPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMidPrice(double value) {
      bitField0_ |= 0x00000008;
      midPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double midPrice = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMidPrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      midPrice_ = 0D;
      onChanged();
      return this;
    }

    private double askPrice_ ;
    /**
     * <code>optional double askPrice = 10;</code>
     * @return Whether the askPrice field is set.
     */
    @java.lang.Override
    public boolean hasAskPrice() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional double askPrice = 10;</code>
     * @return The askPrice.
     */
    @java.lang.Override
    public double getAskPrice() {
      return askPrice_;
    }
    /**
     * <code>optional double askPrice = 10;</code>
     * @param value The askPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAskPrice(double value) {
      bitField0_ |= 0x00000010;
      askPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double askPrice = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAskPrice() {
      bitField0_ = (bitField0_ & ~0x00000010);
      askPrice_ = 0D;
      onChanged();
      return this;
    }

    private double volume_ ;
    /**
     * <code>optional double volume = 11;</code>
     * @return Whether the volume field is set.
     */
    @java.lang.Override
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional double volume = 11;</code>
     * @return The volume.
     */
    @java.lang.Override
    public double getVolume() {
      return volume_;
    }
    /**
     * <code>optional double volume = 11;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(double value) {
      bitField0_ |= 0x00000020;
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double volume = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      bitField0_ = (bitField0_ & ~0x00000020);
      volume_ = 0D;
      onChanged();
      return this;
    }

    private long sourceTimestamp_ ;
    /**
     * <code>optional int64 sourceTimestamp = 12;</code>
     * @return Whether the sourceTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasSourceTimestamp() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int64 sourceTimestamp = 12;</code>
     * @return The sourceTimestamp.
     */
    @java.lang.Override
    public long getSourceTimestamp() {
      return sourceTimestamp_;
    }
    /**
     * <code>optional int64 sourceTimestamp = 12;</code>
     * @param value The sourceTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setSourceTimestamp(long value) {
      bitField0_ |= 0x00000040;
      sourceTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 sourceTimestamp = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      sourceTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long arrivalTimestamp_ ;
    /**
     * <code>optional int64 arrivalTimestamp = 13;</code>
     * @return Whether the arrivalTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasArrivalTimestamp() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int64 arrivalTimestamp = 13;</code>
     * @return The arrivalTimestamp.
     */
    @java.lang.Override
    public long getArrivalTimestamp() {
      return arrivalTimestamp_;
    }
    /**
     * <code>optional int64 arrivalTimestamp = 13;</code>
     * @param value The arrivalTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setArrivalTimestamp(long value) {
      bitField0_ |= 0x00000080;
      arrivalTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 arrivalTimestamp = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearArrivalTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000080);
      arrivalTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long publishTimestamp_ ;
    /**
     * <code>optional int64 publishTimestamp = 14;</code>
     * @return Whether the publishTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasPublishTimestamp() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int64 publishTimestamp = 14;</code>
     * @return The publishTimestamp.
     */
    @java.lang.Override
    public long getPublishTimestamp() {
      return publishTimestamp_;
    }
    /**
     * <code>optional int64 publishTimestamp = 14;</code>
     * @param value The publishTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setPublishTimestamp(long value) {
      bitField0_ |= 0x00000100;
      publishTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 publishTimestamp = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublishTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000100);
      publishTimestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marketdata.Quote)
  }

  // @@protoc_insertion_point(class_scope:marketdata.Quote)
  private static final org.broker.marketdata.protos.Quote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.broker.marketdata.protos.Quote();
  }

  public static org.broker.marketdata.protos.Quote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Quote>
      PARSER = new com.google.protobuf.AbstractParser<Quote>() {
    @java.lang.Override
    public Quote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Quote(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Quote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Quote> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.broker.marketdata.protos.Quote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

